version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: vipulsemwal
      POSTGRES_PASSWORD: 8800713473
      POSTGRES_DB: sultanChand
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
